### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by ZuraGuerra** [ZuraGuerra/versilia#1]
- [ ] Landing bonito
- [ ] Index de Colecciones (categorías de artista) bonito
- [ ] Show de Gafas bonito
- [x] Subir imágenes
- [ ] "Pagos" (pagos-pagos, si me da tiempo)
- [ ] Show de Artista bonito
- [ ] Ponerle password al admin
